### ISSUE TITLE
E2E test fails: Calendar Body and Calendar Header

### ISSUE THREAD

**Issue by htdat** [Automattic/Edit-Flow#637]
## Expected/Desired Behavior

No error. 

## Actual Behavior

Link: https://github.com/Automattic/Edit-Flow/actions/runs/773363262
This E2E test run shows these errors (I am logging this here as GitHub Actions logs will be purged after a period of time): 

```
Run npm run test-e2e

> edit-flow@2.0.0 test-e2e /home/runner/work/Edit-Flow/Edit-Flow
> wp-scripts test-e2e --config tests/e2e/jest.config.js

Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
FAIL tests/e2e/specs/calendar-body.test.js (25.231s)
  ● Calendar Body › expects a scheduled post can be dragged and dropped

    expect(received).not.toContain(expected) // indexOf

    Expected value: not "Scheduled Post"
    Received array:     ["Scheduled Post", "Published Post"]

      94 |         expect(await scheduledPostDay.evaluate((node) => {
      95 |             return Array.prototype.slice.call(node.querySelectorAll('.item-headline.post-title strong')).map((n) => n.innerText)
    > 96 |         })).not.toContain('Scheduled Post');
         |                 ^
      97 |     });
      98 | });

      at Object._callee3$ (specs/calendar-body.test.js:96:17)
      at asyncGeneratorStep (specs/calendar-body.test.js:7:103)
      at _next (specs/calendar-body.test.js:9:194)

FAIL tests/e2e/specs/calendar-header.test.js
  ● Calendar Header › expects a user can select a value for all filters save them and reset them

    TypeError: Cannot read property 'click' of undefined

      2 |     const categoryPanelButton = await page.$x('//button[text()="Categories"]');
      3 | 
    > 4 |     await categoryPanelButton[0].click();
        |                                  ^
      5 | 
      6 |     await page.waitForXPath(
      7 |         '//button[text()="Add New Category"]',

      at _callee$ (utils/index.js:4:34)
      at asyncGeneratorStep (utils/index.js:8:103)
      at _next (utils/index.js:10:194)

PASS tests/e2e/specs/editorial-comments.test.js (6.691s)
PASS tests/e2e/specs/simple.test.js

Test Suites: 2 failed, 2 passed, 4 total
Tests:       2 failed, 4 passed, 6 total
Snapshots:   0 total
Time:        37.658s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edit-flow@2.0.0 test-e2e: `wp-scripts test-e2e --config tests/e2e/jest.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edit-flow@2.0.0 test-e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-22T07_35_31_638Z-debug.log
Error: Process completed with exit code 1.
``` 

## Steps to Reproduce the Problem

I have not tried to reproduce this issue yet but this GH action runs with PHP 7.4 and WP 5.7.

**Comment by htdat** [comment]
It seems NOT an issue with Edit Flow itself as recently all `E2E and JS tests` are all good.
